services:
    web-login:
        build: .
        ports:
            - "8080:80"
        environment:
            - JWT_SECRET_KEY=your_secret_key
        # Mount the folder to the container for development
        # Remove this in production
        volumes:
            - ./:/var/www/html/
